// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4VF132jwDVCVIzBMtt6oDvkvSe67Kwmk',
    appId: '1:799398641805:web:0512aabda328f1647722c4',
    messagingSenderId: '799398641805',
    projectId: 'sahayak-34321',
    authDomain: 'sahayak-34321.firebaseapp.com',
    storageBucket: 'sahayak-34321.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_URwsu-07K5uqavYrAl0EP9hMJpGKmYY',
    appId: '1:799398641805:android:36c9bf4065e76b4d7722c4',
    messagingSenderId: '799398641805',
    projectId: 'sahayak-34321',
    storageBucket: 'sahayak-34321.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyN1B_5MlRJpRbfIIwWCBZjFjaHnFn8zQ',
    appId: '1:799398641805:ios:0049f296967acc857722c4',
    messagingSenderId: '799398641805',
    projectId: 'sahayak-34321',
    storageBucket: 'sahayak-34321.firebasestorage.app',
    iosBundleId: 'com.example.sahayak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyN1B_5MlRJpRbfIIwWCBZjFjaHnFn8zQ',
    appId: '1:799398641805:ios:0049f296967acc857722c4',
    messagingSenderId: '799398641805',
    projectId: 'sahayak-34321',
    storageBucket: 'sahayak-34321.firebasestorage.app',
    iosBundleId: 'com.example.sahayak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4VF132jwDVCVIzBMtt6oDvkvSe67Kwmk',
    appId: '1:799398641805:web:2fca85e369b0776f7722c4',
    messagingSenderId: '799398641805',
    projectId: 'sahayak-34321',
    authDomain: 'sahayak-34321.firebaseapp.com',
    storageBucket: 'sahayak-34321.firebasestorage.app',
  );
}
